// Copyright (c) 2018, The TurtleCoin Developers
// Copyright (c) 2018, The DeroGold Association
//
// Please see the included LICENSE file for more information

#pragma once

const std::string asciiArt =
"                                                                                \n"
"                            .     .... .....                                    \n"
"                         .     .  ..;cddol;'.  .     ..                         \n"
"                           .. ..,:oxOOkkkkkxo:,..   ..                          \n"
"                  .     .  ..;lxO0OOOOOkkkkkkkxdc;'..    .                      \n"
"              .   .  .  .,cdO00000OOOOOOOOkkkkkkxo;...   ..  .  .  .   ..       \n"
"          ..     .  ..;ok0KKK0000000OOOOOOkOkdl;'.       ..      .              \n"
"        ..   ..  .,cdOKXKKKKKK000000OOOOOkdc,..  ... ..';cc;'..                 \n"
"..  .    ..  ..:okKXXXXXXKKKKKK00000Oko:;'.. ..   ..,:odxdddol:,.. ...  .       \n"
"..  .  .  .,cx0NNNNXXXXXXXKKKKKKK0xl;'.   .   ..';ldxxxxxxxdddddoc,...          \n"
".   . ..:oOXWWWNNNNNNXXXXXXKKK0xc,.. .     ..,coxkkkkxxxxxxxddddddol,.          \n"
"  .. .:KWMWWWWWNNNNNNNXXXXKOd:'.  . ..  . .:xOOOkkkkkkxxxxxxddddl:'..           \n"
"  .. .oWMMMWWWWWWNNNNNNKkl;.. ...  ...  . .lOOOOOkkkkkkkxxxxdc;'.. .    ..      \n"
"   . .oWMMMMWWWWWWWN0xc,.  ...  .':c. ... .lOOOOOOOkkkkkxoc,..  ..   ..,,.  .  .\n"
"   . .oWMMMMMWWWN0d:'. .  . ..;lx0Kk' ... .l0OOOOOOOkxo:'.. ..   ..';cod:. .  . \n"
"   . .oWMMMMWXkl;.. ...  .':dOKXXKXk' ... .l00OOOOxl;'.  ..  ...;coddddd:. . .  \n"
"     .oWMWKxc'.  ..  . .;xKXNXXXXXXk' ... .l00Odc,.. .. . ..':ldxxxdddddc. .. . \n"
"   . .cko;.. ...   . . .oNNNNXXXXXXk' ... .co:'.. ...  ..;cdxkxxxxxdddddc. .   .\n"
"     ...  ... ..;:. .. .oNNNNNXXXXXk' . . ...  ... ..,:oxkkkkkxxxxxxxdddc. . .  \n"
"  .    ..  .':d0NK; .. .dNNNNNNXXXXk' .    ...  ..;lxkOOOkkkkkkkxxxxxxdd:. . .. \n"
"  .  .  .,lkXWMMMK; .. .dNNNNNNNXXNO' .     ..,cdk00OOOOOOOkkkkkkxxxdl:'..   .. \n"
" .   .,o0NMMMMMMMK; .. .dWWNNNNNNXNO' ... .,ok0K00000OOOOOOOkkkkkdl;'.  .  ..   \n"
" ..  .oWMMMMMMMMMK; .. .dWWWNNNNNNNO' ... .oKKKK000000OOOOOOOkoc,..  ..    ..   \n"
"     .oWMMMMMMMMMK; .. .dWWWWWNNNNNO' ... .oKKKKK000000OOOko:'..  ..  .... .  . \n"
"  . .oWMMMMMMMMMK; .. .dWWWWWWNNNNO' ... .oXKKKKK0000Oxl;.. ..   ..';ldc. . .   \n"
"   . .oWMMMMMMMMMK; .. .dWWWWWWWNNNO' ... .oXKKKKKKOdc,.. ..   ..,coxkxkl. .    \n"
"   . .oWMMMMMMMMMK; .. .dWMWWWWWWNWO, ... .dXXXKko:'.  ...  .':lxkOkkkkkl. .    \n"
"   . .oWMMMMMMMMMK; .. .dMMMWWWWWNW0, ... .dKkl;..   .. ..;cdkOOOOOkkkkkl. .  . \n"
"   . .oWMMMMMMMMMK; .. .dMMMMWWWWWW0, ... .',.  . .  .':ok000OOOOOOOkkkkl. .  . \n"
" . . .oWMMMMMMMMMK; .. .dMMMMMWWWWW0, . .    ... ..;lxOKK000000OOOOOOkkkl. .    \n"
".    .,d0NMMMMMMMK; .. .dMMMMMMWWWW0, .  .. . .':dOKKKKKKK000000OOOOOkdl,. .  . \n"
" ..  . ..;okXWMMMK; .. .dMMMMMMMMWW0, .   ..;lx0XXXXKKKKKKK000000Okdc,..     .. \n"
" .     ..  .'cx0WK; .. .dMMMMMMMMWM0, .';cd0XNNXXXXXXKKKKKKK000ko:'.   ...   .  \n"
"       . .. . ..;c' .. .dMMMMMMMMMMKolkKNNWNNNNNXXXXXXXKKKK0xl;..  ..  ..       \n"
"       .  ..         . .dMMMMMMMMMMWWWWWWWWNNNNNNXXXXXXKOdc,..  .   ....        \n"
"        .. ..    .   . .:ONWMMMMMMMMMWWWWWWWNNNNNNXXKOo:'.  ....  ..            \n"
"          .   ..  .. .....,lkKWMMMMMMMWWWWWWWNNNNKkl;.. ...   ..                \n"
"                        ..  ..:d0NMMMMMWWWWWWN0dc'.  ..                         \n"
"                            ..  .,lkXWMMMWXOo;.. ...   .                        \n"
"                       .     .     .':dxdl,.  .. ..  ....                       \n"
"                         .  .  .  ...     .... ..  ..  ..                       \n"
"                       Copyright (c) 2019 - Tellurium                           \n";
